name: script

on:
  push:
    branches: 
      - production

jobs:
  script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install Packages
        run: |
          install.packages("data.table")
          install.packages("xml2")
          install.packages("httr")
          install.packages("rvest")
          install.packages("fuzzyjoin")  
        shell: Rscript {0}



