name: script

on:
  push:
    branches: 
      - production

jobs:

  script:
    
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
        
      - name: Install packages
        run: |
          R -e 'install.packages("data.table")'
          R -e 'install.packages("xml2")'
          R -e 'install.packages("httr")'
          R -e 'install.packages("rvest")'
          R -e 'install.packages("fuzzyjoin")'
          
      - name: Scrape
        run: Rscript script_scrape_salaries_projections.R
